repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.23.0  # Use the latest version
    hooks:
      - id: eslint
        args: ['--config', 'eslint.config.js', '--fix']
